#!/usr/bin/env bash
###############################################################################
# install.sh
#
# Instalador del sistema ZSH modular.
#
# Características:
# - Detecta Debian/Ubuntu
# - Instala dependencias básicas
# - Hace backup de configuración existente
# - Crea enlaces simbólicos
# - Configura ZSH como shell por defecto
###############################################################################

set -e

###############################################################################
# Variables
###############################################################################

ZSH_DIR="$$HOME/.zsh"
ZSHRC="$ZSH_DIRrc"
BACKUP="$ZSH_DIRrc.backup.$(date +%Y%m%d%H%M%S)"

###############################################################################
# Detectar sistema
###############################################################################

detect_os() {
    if [[ -f /etc/debian_version ]]; then
        echo "debian"
    else
        echo "unsupported"
    fi
}

OS="$(detect_os)"

if [[ "$OS" == "unsupported" ]]; then
    echo "Sistema no soportado"
    exit 1
fi

###############################################################################
# Instalar dependencias (Debian)
###############################################################################

install_deps_debian() {

    sudo apt update

    sudo apt install -y \
        zsh \
        zsh-autosuggestions \
        zsh-syntax-highlighting \
        git \
        fzf \
        eza \
        direnv \
        zoxide \
        bat \
        curl

    echo "Comprobando la existencia de plugins externos"

    if [ -d "$ZSH_DIR/externos" ]; then
        echo "Directorio Externos Existe"
    else
        echo "Creando Directorio Externos"
        mkdir -p $ZSH_DIR/externos
    fi

    echo "Instalando plugins externos"

    if [ -d "$ZSH_DIR/externos/zsh-history-substring-search" ]; then
        echo "Actualizando Plugin zsh-history-substring-search"
        cd $ZSH_DIR/externos/zsh-history-substring-search
        git fetch && git pull
    else
        echo "Descargando zsh-history-substring-search"
        sudo git clone https://github.com/zsh-users/zsh-history-substring-search $ZSH_DIR/externos/zsh-history-substring-search
    fi
    
    if [ -d "$ZSH_DIR/externos/zsh-completions" ]; then
        echo "Actualizando Plugin zsh-completions"
        cd $ZSH_DIR/externos/zsh-completions
        git fetch && git pull
    else
        echo "Descargando zsh-completions"
        sudo git clone https://github.com/zsh-users/zsh-completions $ZSH_DIR/externos/zsh-completions
    fi

    echo "Dependencias instaladas"
}

###############################################################################
# Backup de configuración existente
###############################################################################

backup_zshrc() {

    if [[ -f "$ZSHRC" ]]; then
        cp "$ZSHRC" "$BACKUP"
        echo "Backup creado en $BACKUP"
    fi
}

###############################################################################
# Crear .zshrc principal
###############################################################################

create_zshrc() {

    cat > "$ZSHRC" <<'EOF'
###############################################################################
# Generated by ZSH modular system
###############################################################################

export ZSH_CONFIG="$ZSH_DIR"

source $ZSH_CONFIG/core/options.zsh
source $ZSH_CONFIG/core/exports.zsh
source $ZSH_CONFIG/core/colors.zsh
source $ZSH_CONFIG/core/icons.zsh
source $ZSH_CONFIG/core/history.zsh
source $ZSH_CONFIG/core/functions.zsh
source $ZSH_CONFIG/core/hooks.zsh
source $ZSH_CONFIG/core/prompt.zsh

source $ZSH_CONFIG/modules/git.zsh
source $ZSH_CONFIG/modules/docker.zsh
source $ZSH_CONFIG/modules/python.zsh
source $ZSH_CONFIG/modules/ssh.zsh
source $ZSH_CONFIG/modules/root.zsh
source $ZSH_CONFIG/modules/timer.zsh

source $ZSH_CONFIG/plugins/fzf.zsh
source $ZSH_CONFIG/plugins/zoxide.zsh
source $ZSH_CONFIG/plugins/direnv.zsh
source $ZSH_CONFIG/plugins/eza.zsh
source $ZSH_CONFIG/plugins/completions.zsh
source $ZSH_CONFIG/plugins/autosuggestions.zsh
source $ZSH_CONFIG/plugins/syntax-highlighting.zsh
source $ZSH_CONFIG/plugins/history-substring-search.zsh
EOF

    echo ".zshrc generado"
}

###############################################################################
# Cambiar shell por defecto
###############################################################################

change_shell() {

    if command -v zsh >/dev/null 2>&1; then
        chsh -s "$(which zsh)"
        echo "Shell cambiado a zsh"
    fi
}

###############################################################################
# Ejecución
###############################################################################

echo "Instalando sistema ZSH modular..."

if [[ "$OS" == "debian" ]]; then
    install_deps_debian
fi

backup_zshrc
create_zshrc
change_shell

echo "Instalación completada. Reinicia la sesión."